import type { Metadata } from 'next';
import Link from 'next/link';

import ScrollAnimate from '../ScrollAnimate';
import SiteHeader from '../SiteHeader';
import { runSecurityAudit } from '@/lib/security-lab/audit-engine';
import {
  securityLabScenarios,
  securitySkillStatus,
} from '@/lib/security-lab/scenarios';
import type { Severity } from '@/lib/security-lab/types';

export const metadata: Metadata = {
  title: 'Security Lab | MCP Hub',
  description:
    'Interactive defensive security audit lab for MCP-enabled applications, focused on permissions, prompt exposure, tool safety, and auditability.',
};

const severityStyles: Record<Severity, string> = {
  critical: 'border-red-400/35 bg-red-500/10 text-red-100',
  high: 'border-orange-300/35 bg-orange-400/10 text-orange-100',
  medium: 'border-yellow-300/35 bg-yellow-300/10 text-yellow-50',
  low: 'border-emerald-300/35 bg-emerald-400/10 text-emerald-50',
};

const severityLabelStyles: Record<Severity, string> = {
  critical: 'bg-red-500 text-white',
  high: 'bg-orange-400 text-[#1f2937]',
  medium: 'bg-[#FFE492] text-[#043873]',
  low: 'bg-emerald-400 text-[#043873]',
};

const metricDescriptions = [
  {
    label: 'Least Privilege',
    value: 'File, browser, and deploy access should stay scoped to the active task.',
  },
  {
    label: 'Data Minimization',
    value: 'Prompt context should exclude secrets and private notes before they reach the model.',
  },
  {
    label: 'Traceability',
    value: 'Every sensitive decision should leave behind a reviewable audit trail.',
  },
];

function formatCapabilityLabel(value: string) {
  return value.replace(/-/g, ' ');
}

function riskBand(score: number) {
  if (score >= 80) return 'Critical attention';
  if (score >= 55) return 'High risk';
  if (score >= 30) return 'Needs hardening';
  return 'Mostly controlled';
}

export default async function SecurityLabPage({
  searchParams,
}: {
  searchParams?: Promise<{ scenario?: string | string[] }>;
}) {
  const params = (await searchParams) ?? {};
  const slug =
    typeof params.scenario === 'string'
      ? params.scenario
      : securityLabScenarios[0].slug;

  const activeScenario =
    securityLabScenarios.find((scenario) => scenario.slug === slug) ??
    securityLabScenarios[0];

  const audit = runSecurityAudit(activeScenario);

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#043873] font-sans text-white">
      <SiteHeader currentPage="security" />

      <section className="relative overflow-hidden px-8 py-20 lg:px-[220px] lg:py-[120px]">
        <div className="absolute left-20 top-10 h-[340px] w-[340px] rounded-full bg-[#4F9CF9]/20 blur-[110px]"></div>
        <div className="absolute right-16 top-8 h-[320px] w-[320px] rounded-full bg-[#FFE492]/15 blur-[110px]"></div>
        <ScrollAnimate className="relative z-10 mx-auto flex max-w-[1200px] flex-col gap-10">
          <div className="inline-flex w-fit items-center gap-3 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm font-medium text-[#C4DEFD] backdrop-blur">
            <span className="h-2.5 w-2.5 animate-pulse rounded-full bg-[#FFE492]"></span>
            Defensive audit lab for MCP-enabled applications
          </div>

          <div className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr]">
            <div className="space-y-6">
              <h1 className="text-5xl font-bold leading-tight tracking-tight text-white md:text-[64px]">
                Security Lab
              </h1>
              <p className="text-[18px] leading-[30px] text-white/90">
                This route turns the MCP Hub project into an educational security audit
                environment. Instead of simulating offensive behavior, it scores realistic
                design decisions around permissions, prompt exposure, tool execution, and
                logging.
              </p>
              <p className="text-[18px] leading-[30px] text-white/80">
                The active scenario is <span className="font-semibold text-[#FFE492]">{activeScenario.title}</span>.
                Its findings are generated by a small rule-based engine so the feature stays
                explainable and easy to remove if the project pivots toward the MFA backup idea.
              </p>
            </div>

            <div className="rounded-[32px] border border-white/10 bg-white/[0.06] p-8 shadow-2xl backdrop-blur">
              <div className="flex items-start justify-between gap-5">
                <div>
                  <p className="text-xs font-mono uppercase tracking-[0.22em] text-[#C4DEFD]">
                    Live audit score
                  </p>
                  <p className="mt-3 text-6xl font-bold text-white">{audit.riskScore}</p>
                  <p className="mt-3 text-lg font-medium text-[#FFE492]">{riskBand(audit.riskScore)}</p>
                </div>
                <div className="rounded-3xl border border-white/10 bg-[#032b59]/80 px-5 py-4 text-right">
                  <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                    Threat focus
                  </p>
                  <p className="mt-2 max-w-[220px] text-sm leading-6 text-white/75">
                    {activeScenario.threatModel}
                  </p>
                </div>
              </div>

              <div className="mt-8 grid gap-4 md:grid-cols-2">
                {(['critical', 'high', 'medium', 'low'] as Severity[]).map((severity) => (
                  <div
                    key={severity}
                    className={`rounded-2xl border px-4 py-4 ${severityStyles[severity]}`}
                  >
                    <p className="text-xs font-mono uppercase tracking-[0.18em]">
                      {severity}
                    </p>
                    <p className="mt-2 text-3xl font-bold">{audit.findingCounts[severity]}</p>
                    <p className="mt-1 text-sm text-current/80">findings in this scenario</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            {metricDescriptions.map((item) => (
              <div key={item.label} className="rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur">
                <p className="text-xs uppercase tracking-[0.2em] text-[#C4DEFD]">{item.label}</p>
                <p className="mt-3 text-base leading-7 text-white/85">{item.value}</p>
              </div>
            ))}
          </div>
        </ScrollAnimate>
      </section>

      <section className="bg-white px-8 py-20 text-[#043873] lg:px-[220px] lg:py-[120px]">
        <ScrollAnimate className="mx-auto flex max-w-[1200px] flex-col gap-10">
          <div className="max-w-[760px] space-y-4">
            <h2 className="text-4xl font-bold tracking-tight md:text-[56px]">
              Scenario Selector
            </h2>
            <p className="text-[18px] leading-[30px] text-[#043873]/80">
              Each preset models one defensive audit angle from the lab notes: permissions,
              prompt exposure, tool invocation, or incident visibility.
            </p>
          </div>

          <div className="grid gap-6 lg:grid-cols-2">
            {securityLabScenarios.map((scenario) => {
              const isActive = scenario.slug === activeScenario.slug;

              return (
                <Link
                  key={scenario.slug}
                  href={`/security-lab?scenario=${scenario.slug}`}
                  className={`rounded-[28px] border p-8 shadow-lg transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl ${
                    isActive
                      ? 'border-[#4F9CF9] bg-[#043873] text-white'
                      : 'border-[#dbe8f7] bg-white/90 text-[#043873]'
                  }`}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p
                        className={`text-xs font-mono uppercase tracking-[0.22em] ${
                          isActive ? 'text-[#C4DEFD]' : 'text-[#4F9CF9]'
                        }`}
                      >
                        Audit scenario
                      </p>
                      <h3 className="mt-3 text-2xl font-bold">{scenario.title}</h3>
                    </div>
                    <span
                      className={`rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] ${
                        isActive ? 'bg-white/10 text-[#FFE492]' : 'bg-[#EAF4FF] text-[#043873]'
                      }`}
                    >
                      {isActive ? 'active' : 'open'}
                    </span>
                  </div>
                  <p className={`mt-5 leading-relaxed ${isActive ? 'text-white/82' : 'text-[#043873]/78'}`}>
                    {scenario.summary}
                  </p>
                  <p className={`mt-5 text-sm leading-6 ${isActive ? 'text-[#C4DEFD]' : 'text-[#4F9CF9]'}`}>
                    {scenario.labGoal}
                  </p>
                </Link>
              );
            })}
          </div>
        </ScrollAnimate>
      </section>

      <section className="bg-[#043873] px-8 py-20 text-white lg:px-[220px] lg:py-[120px]">
        <ScrollAnimate className="mx-auto grid max-w-[1200px] gap-8 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="rounded-[32px] border border-white/10 bg-white/5 p-8 shadow-2xl backdrop-blur">
            <div className="max-w-[720px] space-y-5">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#C4DEFD]">
                Attack surface snapshot
              </p>
              <h2 className="text-4xl font-bold tracking-tight md:text-[52px]">
                What this assistant can currently reach
              </h2>
              <p className="text-[18px] leading-[30px] text-white/82">
                The lab keeps the system model visible so each finding stays grounded in a
                concrete capability rather than abstract fear.
              </p>
            </div>

            <div className="mt-8 grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl border border-white/10 bg-[#032b59]/70 p-5">
                <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                  Filesystem scope
                </p>
                <p className="mt-3 text-2xl font-bold text-white">
                  {formatCapabilityLabel(activeScenario.posture.filesystemScope)}
                </p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-[#032b59]/70 p-5">
                <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                  Browser scope
                </p>
                <p className="mt-3 text-2xl font-bold text-white">
                  {formatCapabilityLabel(activeScenario.posture.browserScope)}
                </p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-[#032b59]/70 p-5">
                <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                  Command mode
                </p>
                <p className="mt-3 text-2xl font-bold text-white">
                  {formatCapabilityLabel(activeScenario.posture.commandExecution)}
                </p>
              </div>
              <div className="rounded-2xl border border-white/10 bg-[#032b59]/70 p-5">
                <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                  Audit coverage
                </p>
                <p className="mt-3 text-2xl font-bold text-white">
                  {formatCapabilityLabel(activeScenario.posture.auditCoverage)}
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-[#FFE492] to-[#f8df7e] p-8 text-[#043873] shadow-2xl">
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#4F9CF9]">
              Threat model
            </p>
            <h3 className="mt-4 text-3xl font-bold">Why this scenario matters</h3>
            <p className="mt-5 text-[18px] leading-[30px] text-[#043873]/82">
              {activeScenario.threatModel}
            </p>
            <div className="mt-8 space-y-4">
              {activeScenario.exposureNotes.map((note) => (
                <div
                  key={note}
                  className="flex items-start gap-3 rounded-2xl border border-[#043873]/10 bg-white/50 p-4"
                >
                  <span className="mt-1 text-[#4F9CF9]">-</span>
                  <p className="leading-relaxed text-[#043873]/82">{note}</p>
                </div>
              ))}
            </div>
          </div>
        </ScrollAnimate>
      </section>

      <section className="bg-gradient-to-br from-[#C4DEFD] via-[#dde9f8] to-[#f0f6ff] px-8 py-20 text-[#043873] lg:px-[220px] lg:py-[120px]">
        <ScrollAnimate className="mx-auto flex max-w-[1200px] flex-col gap-10">
          <div className="max-w-[760px] space-y-4">
            <h2 className="text-4xl font-bold tracking-tight md:text-[56px]">
              Findings and Mitigations
            </h2>
            <p className="text-[18px] leading-[30px] text-[#043873]/80">
              The audit engine raises rule-based findings so each issue can be explained,
              defended, and later removed without untangling a large feature dependency graph.
            </p>
          </div>

          <div className="grid gap-6">
            {audit.findings.map((finding) => (
              <div
                key={`${finding.id}-${finding.title}`}
                className="rounded-[30px] border border-white bg-white/90 p-8 shadow-lg"
              >
                <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
                  <div className="max-w-[760px]">
                    <div className="flex flex-wrap items-center gap-3">
                      <span className="rounded-full bg-[#043873]/5 px-4 py-2 text-xs font-mono tracking-[0.18em] text-[#4F9CF9]">
                        {finding.id}
                      </span>
                      <span
                        className={`rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] ${severityLabelStyles[finding.severity]}`}
                      >
                        {finding.severity}
                      </span>
                      <span className="rounded-full border border-[#d7e8ff] bg-[#EAF4FF] px-4 py-2 text-xs font-medium text-[#043873]">
                        {finding.theme}
                      </span>
                    </div>
                    <h3 className="mt-5 text-2xl font-bold text-[#043873]">{finding.title}</h3>
                    <p className="mt-4 leading-relaxed text-[#043873]/80">{finding.detail}</p>
                  </div>

                  <div className="w-full rounded-[28px] bg-[#043873] p-6 text-white lg:max-w-[360px]">
                    <p className="text-xs font-mono uppercase tracking-[0.18em] text-[#C4DEFD]">
                      Recommended hardening
                    </p>
                    <p className="mt-4 text-[17px] leading-[30px] text-white/84">
                      {finding.mitigation}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </ScrollAnimate>
      </section>

      <section className="bg-white px-8 py-20 text-[#043873] lg:px-[220px] lg:py-[120px]">
        <ScrollAnimate className="mx-auto grid max-w-[1200px] gap-8 lg:grid-cols-[1fr_1fr]">
          <div className="rounded-[32px] border border-[#dbe8f7] bg-white/90 p-8 shadow-lg">
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#4F9CF9]">
              Security skills status
            </p>
            <h2 className="mt-4 text-4xl font-bold tracking-tight md:text-[48px]">
              Verified for this work session
            </h2>
            <div className="mt-8 space-y-4">
              {securitySkillStatus.map((skill) => (
                <div
                  key={skill.name}
                  className="rounded-2xl border border-[#dbe8f7] bg-[#f8fbff] p-5"
                >
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <p className="text-lg font-semibold text-[#043873]">{skill.name}</p>
                    <span className="rounded-full bg-[#043873] px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#FFE492]">
                      {skill.status}
                    </span>
                  </div>
                  <p className="mt-3 leading-relaxed text-[#043873]/75">{skill.detail}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-[32px] border border-[#dbe8f7] bg-gradient-to-br from-[#043873] to-[#032b59] p-8 text-white shadow-lg">
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#C4DEFD]">
              Incident timeline
            </p>
            <h2 className="mt-4 text-4xl font-bold tracking-tight md:text-[48px]">
              Reviewable event stream
            </h2>
            <div className="mt-8 space-y-4">
              {activeScenario.events.map((event) => (
                <div
                  key={`${event.time}-${event.action}`}
                  className="rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur"
                >
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <p className="text-sm font-mono tracking-[0.18em] text-[#FFE492]">{event.time}</p>
                    <span className="rounded-full bg-white/10 px-3 py-1 text-xs uppercase tracking-[0.18em] text-[#C4DEFD]">
                      {event.status}
                    </span>
                  </div>
                  <p className="mt-3 text-lg font-semibold">{event.action}</p>
                  <p className="mt-2 text-sm uppercase tracking-[0.18em] text-[#C4DEFD]">
                    {event.actor}
                  </p>
                  <p className="mt-3 leading-relaxed text-white/78">{event.detail}</p>
                </div>
              ))}
            </div>
          </div>
        </ScrollAnimate>
      </section>

      <section className="bg-[#FFE492] px-8 py-20 text-[#043873] lg:px-[220px] lg:py-[120px]">
        <ScrollAnimate className="mx-auto max-w-[1200px] rounded-[32px] bg-white/75 p-10 shadow-xl backdrop-blur">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-[760px] space-y-4">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#4F9CF9]">
                Reversible by design
              </p>
              <h2 className="text-4xl font-bold tracking-tight md:text-[52px]">
                Small surface area, easy to replace later
              </h2>
              <p className="text-[18px] leading-[30px] text-[#043873]/80">
                The lab is intentionally isolated to one route plus a small local rule engine. If
                the project switches to the MFA fallback, we can remove this route cleanly without
                untangling shared business logic.
              </p>
            </div>

            <Link
              href="/codex-in-practice"
              className="inline-flex items-center justify-center rounded-xl bg-[#043873] px-8 py-4 text-[18px] font-medium text-white transition-all hover:bg-[#032b59] hover:shadow-lg"
            >
              Continue Through The Site
            </Link>
          </div>
        </ScrollAnimate>
      </section>
    </div>
  );
}
