import type { AccessScenario, MfaMethod } from './types';

export const mfaMethods: MfaMethod[] = [
  {
    id: 'password',
    name: 'Password',
    category: 'Knowledge',
    shortDescription: 'The primary factor that starts the sign-in flow.',
    securityValue: 'Provides the first identity checkpoint and enables step-up verification.',
    limitations: 'Weak alone because passwords can be reused, guessed, or phished.',
  },
  {
    id: 'totp',
    name: 'TOTP / Authenticator',
    category: 'Possession',
    shortDescription: 'A 6-digit rotating code generated by an authenticator app.',
    securityValue: 'Strong against simple password theft and works offline.',
    limitations: 'Can still be phished in real time if the user submits it to a fake site.',
    generatedCredential: 'totp',
  },
  {
    id: 'email-otp',
    name: 'Email OTP',
    category: 'Possession',
    shortDescription: 'A one-time code delivered through email.',
    securityValue: 'Easy fallback channel for account recovery or low-friction MFA.',
    limitations: 'Depends on mailbox security and can be slower than app-based factors.',
    generatedCredential: 'email',
  },
  {
    id: 'sms-otp',
    name: 'SMS OTP',
    category: 'Possession',
    shortDescription: 'A one-time code delivered over SMS.',
    securityValue: 'Widely accessible and familiar for many users.',
    limitations: 'Weaker than modern methods because of SIM-swap and interception risks.',
    generatedCredential: 'sms',
  },
  {
    id: 'push',
    name: 'Push Approval',
    category: 'Possession',
    shortDescription: 'The user confirms a login request from a trusted mobile app.',
    securityValue: 'Provides fast step-up verification and richer context than plain OTP.',
    limitations: 'Can be abused through MFA fatigue if repeated requests are not controlled.',
  },
  {
    id: 'webauthn',
    name: 'FIDO2 / WebAuthn Passkey',
    category: 'Possession',
    shortDescription: 'A phishing-resistant cryptographic login using a device-bound credential.',
    securityValue: 'Strongest modern web factor because it resists replay and phishing better.',
    limitations: 'Requires compatible devices and browser support.',
  },
  {
    id: 'biometric',
    name: 'Biometric Verification',
    category: 'Inherence',
    shortDescription: 'Local face or fingerprint confirmation on the user device.',
    securityValue: 'Convenient proof of user presence and strong local friction reduction.',
    limitations: 'Usually works best when paired with device security rather than alone.',
  },
];

export const accessScenarios: AccessScenario[] = [
  {
    slug: 'student-portal-normal-login',
    title: 'Normal Student Portal Login',
    audience: 'Returning student on a known device',
    description:
      'A low-risk login where the system still enforces password plus an authenticator code.',
    riskLevel: 'low',
    triggers: ['Known device', 'Expected location', 'No unusual retry pattern'],
    requiredMethods: ['password', 'totp'],
    recommendedMethods: ['password', 'totp', 'push'],
    alertReasons: [],
  },
  {
    slug: 'new-device-step-up',
    title: 'New Device Step-Up Verification',
    audience: 'Valid user logging in from an unknown browser',
    description:
      'The system raises the assurance level because the device is not recognized.',
    riskLevel: 'medium',
    triggers: ['New browser fingerprint', 'No previous session on this device'],
    requiredMethods: ['password', 'totp', 'email-otp'],
    recommendedMethods: ['password', 'totp', 'email-otp', 'webauthn'],
    alertReasons: ['New device detected', 'Step-up verification required'],
  },
  {
    slug: 'suspicious-location-attempt',
    title: 'Suspicious Location Attempt',
    audience: 'Access request from an unusual location',
    description:
      'The account is challenged with stronger possession factors and generates an alert.',
    riskLevel: 'high',
    triggers: ['Impossible travel pattern', 'Unrecognized network', 'Risk engine escalation'],
    requiredMethods: ['password', 'push', 'webauthn'],
    recommendedMethods: ['password', 'push', 'webauthn', 'biometric'],
    alertReasons: ['Unusual location', 'High-risk login attempt'],
  },
  {
    slug: 'mfa-fatigue-attack',
    title: 'MFA Fatigue / Unauthorized Access Attempt',
    audience: 'Potential attacker repeatedly triggering approvals',
    description:
      'The system shows repeated prompts, flags the event, and requires a stronger phishing-resistant factor.',
    riskLevel: 'critical',
    triggers: ['Repeated push prompts', 'Failed OTP sequence', 'Rapid retry burst'],
    requiredMethods: ['password', 'webauthn', 'biometric'],
    recommendedMethods: ['password', 'webauthn', 'biometric', 'push'],
    alertReasons: [
      'Repeated verification requests detected',
      'Potential MFA fatigue behavior',
      'Security team review required',
    ],
  },
];
